import { ExcalidrawElement } from './types';

/**
 * Returns initial schematic and typography elements that match Screenshot 1 and Screenshot 4
 */
export function getInitialElements(): ExcalidrawElement[] {
  const elements: ExcalidrawElement[] = [];
  let idCounter = 1;
  const nextId = () => `elem_${idCounter++}`;

  // Circuit Schematic elements (matching Screenshot 1)
  const cx = 200;
  const cy = 180;

  // 1. Voltage Source circle with + and -
  elements.push({
    id: nextId(),
    type: 'ellipse',
    x: cx,
    y: cy + 100,
    width: 60,
    height: 60,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'hachure',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [],
    seed: 101,
  });

  // Vs label
  elements.push({
    id: nextId(),
    type: 'text',
    x: cx - 35,
    y: cy + 115,
    width: 30,
    height: 30,
    angle: 0,
    strokeColor: '#ffffff',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 1,
    points: [],
    text: 'Vs',
    fontFamily: 'excalifont',
    fontSize: 24,
    seed: 102,
  });

  // Plus and minus inside source
  elements.push({
    id: nextId(),
    type: 'text',
    x: cx + 22,
    y: cy + 108,
    width: 20,
    height: 20,
    angle: 0,
    strokeColor: '#e03131',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 1,
    points: [],
    text: '+',
    fontFamily: 'excalifont',
    fontSize: 20,
    seed: 103,
  });
  elements.push({
    id: nextId(),
    type: 'text',
    x: cx + 24,
    y: cy + 130,
    width: 20,
    height: 20,
    angle: 0,
    strokeColor: '#e03131',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 1,
    points: [],
    text: '-',
    fontFamily: 'excalifont',
    fontSize: 22,
    seed: 104,
  });

  // Top wire from source to switch
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 30,
    y: cy + 100,
    width: 0,
    height: -60,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 0, y: -60 }],
    seed: 105,
  });
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 30,
    y: cy + 40,
    width: 90,
    height: 0,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 90, y: 0 }],
    seed: 106,
  });

  // Is current label with small arrow
  elements.push({
    id: nextId(),
    type: 'text',
    x: cx + 55,
    y: cy + 10,
    width: 30,
    height: 25,
    angle: 0,
    strokeColor: '#ffffff',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 1,
    points: [],
    text: 'Is',
    fontFamily: 'excalifont',
    fontSize: 20,
    seed: 107,
  });
  elements.push({
    id: nextId(),
    type: 'arrow',
    x: cx + 50,
    y: cy + 32,
    width: 30,
    height: 0,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 1.5,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 30, y: 0 }],
    seed: 108,
  });

  // Switch / MOSFET 'S'
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 120,
    y: cy + 40,
    width: 0,
    height: 35,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 0, y: 35 }],
    seed: 109,
  });
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 120,
    y: cy + 75,
    width: 60,
    height: 0,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 60, y: 0 }],
    seed: 110,
  });
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 180,
    y: cy + 75,
    width: 0,
    height: -35,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 0, y: -35 }],
    seed: 111,
  });
  elements.push({
    id: nextId(),
    type: 'text',
    x: cx + 145,
    y: cy + 10,
    width: 30,
    height: 25,
    angle: 0,
    strokeColor: '#ffffff',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 1,
    points: [],
    text: 'S',
    fontFamily: 'excalifont',
    fontSize: 24,
    seed: 112,
  });

  // Inductor L (middle branch)
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 250,
    y: cy + 40,
    width: 0,
    height: 40,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 0, y: 40 }],
    seed: 113,
  });
  // Inductor coils
  for (let k = 0; k < 4; k++) {
    elements.push({
      id: nextId(),
      type: 'ellipse',
      x: cx + 242,
      y: cy + 80 + k * 16,
      width: 16,
      height: 20,
      angle: 0,
      strokeColor: '#868e96',
      backgroundColor: 'transparent',
      fillStyle: 'transparent',
      strokeWidth: 1.8,
      strokeStyle: 'solid',
      roughness: 1,
      opacity: 1,
      points: [],
      seed: 114 + k,
    });
  }
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 250,
    y: cy + 148,
    width: 0,
    height: 52,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 0, y: 52 }],
    seed: 120,
  });
  elements.push({
    id: nextId(),
    type: 'text',
    x: cx + 270,
    y: cy + 105,
    width: 30,
    height: 25,
    angle: 0,
    strokeColor: '#ffffff',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 1,
    points: [],
    text: 'L',
    fontFamily: 'excalifont',
    fontSize: 24,
    seed: 121,
  });

  // Diode D branch
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 250,
    y: cy + 40,
    width: 70,
    height: 0,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 70, y: 0 }],
    seed: 122,
  });
  // Diode arrow / triangle
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 320,
    y: cy + 25,
    width: 0,
    height: 30,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 0, y: 30 }],
    seed: 123,
  });
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 320,
    y: cy + 25,
    width: 25,
    height: 15,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 25, y: 15 }],
    seed: 124,
  });
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 320,
    y: cy + 55,
    width: 25,
    height: -15,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 25, y: -15 }],
    seed: 125,
  });
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 345,
    y: cy + 25,
    width: 0,
    height: 30,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 0, y: 30 }],
    seed: 126,
  });
  elements.push({
    id: nextId(),
    type: 'text',
    x: cx + 330,
    y: cy + 0,
    width: 30,
    height: 25,
    angle: 0,
    strokeColor: '#ffffff',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 1,
    points: [],
    text: 'D',
    fontFamily: 'excalifont',
    fontSize: 24,
    seed: 127,
  });

  // Capacitor C branch
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 345,
    y: cy + 40,
    width: 100,
    height: 0,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 100, y: 0 }],
    seed: 128,
  });
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 445,
    y: cy + 40,
    width: 0,
    height: 60,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 0, y: 60 }],
    seed: 129,
  });
  // Capacitor plates
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 430,
    y: cy + 100,
    width: 30,
    height: 0,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 30, y: 0 }],
    seed: 130,
  });
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 430,
    y: cy + 115,
    width: 30,
    height: 0,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 30, y: 0 }],
    seed: 131,
  });
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 445,
    y: cy + 115,
    width: 0,
    height: 85,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 0, y: 85 }],
    seed: 132,
  });
  elements.push({
    id: nextId(),
    type: 'text',
    x: cx + 410,
    y: cy + 110,
    width: 30,
    height: 25,
    angle: 0,
    strokeColor: '#ffffff',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 1,
    points: [],
    text: 'C',
    fontFamily: 'excalifont',
    fontSize: 24,
    seed: 133,
  });

  // Load box
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 445,
    y: cy + 40,
    width: 80,
    height: 0,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 80, y: 0 }],
    seed: 134,
  });
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 525,
    y: cy + 40,
    width: 0,
    height: 30,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 0, y: 30 }],
    seed: 135,
  });
  elements.push({
    id: nextId(),
    type: 'rectangle',
    x: cx + 510,
    y: cy + 70,
    width: 30,
    height: 80,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [],
    seed: 136,
  });
  elements.push({
    id: nextId(),
    type: 'text',
    x: cx + 520,
    y: cy + 75,
    width: 20,
    height: 80,
    angle: 0,
    strokeColor: '#ffffff',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 1,
    points: [],
    text: 'L\nO\nA\nD',
    fontFamily: 'excalifont',
    fontSize: 16,
    seed: 137,
  });
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 525,
    y: cy + 150,
    width: 0,
    height: 50,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 0, y: 50 }],
    seed: 138,
  });

  // Vo label
  elements.push({
    id: nextId(),
    type: 'text',
    x: cx + 550,
    y: cy + 105,
    width: 30,
    height: 25,
    angle: 0,
    strokeColor: '#ffffff',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 1,
    points: [],
    text: 'Vo',
    fontFamily: 'excalifont',
    fontSize: 24,
    seed: 139,
  });

  // Bottom return line closing the whole circuit
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 30,
    y: cy + 160,
    width: 0,
    height: 40,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 0, y: 40 }],
    seed: 140,
  });
  elements.push({
    id: nextId(),
    type: 'line',
    x: cx + 30,
    y: cy + 200,
    width: 495,
    height: 0,
    angle: 0,
    strokeColor: '#868e96',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 495, y: 0 }],
    seed: 141,
  });

  // Typography Showcase from Screenshot 4 (below circuit or to the right)
  const tx = 180;
  const ty = 460;

  // Outer container border
  elements.push({
    id: nextId(),
    type: 'rectangle',
    x: tx,
    y: ty,
    width: 660,
    height: 180,
    angle: 0,
    strokeColor: '#d0d0d0',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1.2,
    opacity: 1,
    points: [],
    seed: 201,
  });

  // Table header horizontal line
  elements.push({
    id: nextId(),
    type: 'line',
    x: tx,
    y: ty + 70,
    width: 660,
    height: 0,
    angle: 0,
    strokeColor: '#d0d0d0',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 1,
    points: [{ x: 0, y: 0 }, { x: 660, y: 0 }],
    seed: 202,
  });

  // Vertical column dividers
  const colWidths = [140, 130, 130, 130];
  let curX = tx + colWidths[0];
  for (let c = 0; c < 3; c++) {
    elements.push({
      id: nextId(),
      type: 'line',
      x: curX,
      y: ty,
      width: 0,
      height: 180,
      angle: 0,
      strokeColor: '#d0d0d0',
      backgroundColor: 'transparent',
      fillStyle: 'transparent',
      strokeWidth: 2,
      strokeStyle: 'solid',
      roughness: 1,
      opacity: 1,
      points: [{ x: 0, y: 0 }, { x: 0, y: 180 }],
      seed: 203 + c,
    });
    curX += colWidths[c + 1];
  }

  // Row 1 Text
  elements.push({
    id: nextId(),
    type: 'text',
    x: tx + 20,
    y: ty + 22,
    width: 100,
    height: 25,
    angle: 0,
    strokeColor: '#e0e0e0',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 1,
    points: [],
    text: 'Font name',
    fontFamily: 'excalifont',
    fontSize: 22,
    seed: 210,
  });
  elements.push({
    id: nextId(),
    type: 'text',
    x: tx + 160,
    y: ty + 22,
    width: 100,
    height: 25,
    angle: 0,
    strokeColor: '#e0e0e0',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 1,
    points: [],
    text: 'Excalifont',
    fontFamily: 'excalifont',
    fontSize: 22,
    seed: 211,
  });
  elements.push({
    id: nextId(),
    type: 'text',
    x: tx + 285,
    y: ty + 22,
    width: 110,
    height: 25,
    angle: 0,
    strokeColor: '#e0e0e0',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 1,
    points: [],
    text: 'comic shaans',
    fontFamily: 'comic-shanns',
    fontSize: 20,
    seed: 212,
  });
  elements.push({
    id: nextId(),
    type: 'text',
    x: tx + 420,
    y: ty + 22,
    width: 100,
    height: 25,
    angle: 0,
    strokeColor: '#e0e0e0',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 1,
    points: [],
    text: 'lillita one',
    fontFamily: 'lilita-one',
    fontSize: 20,
    seed: 213,
  });
  elements.push({
    id: nextId(),
    type: 'text',
    x: tx + 560,
    y: ty + 22,
    width: 80,
    height: 25,
    angle: 0,
    strokeColor: '#e0e0e0',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 1,
    points: [],
    text: 'nunito',
    fontFamily: 'nunito',
    fontSize: 20,
    seed: 214,
  });

  // Row 2 Text (Screenshot 4 exact contents: ANURAG SONI / anurag soni)
  elements.push({
    id: nextId(),
    type: 'text',
    x: tx + 12,
    y: ty + 105,
    width: 115,
    height: 25,
    angle: 0,
    strokeColor: '#b0b0b0',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 1,
    points: [],
    text: 'STYLE OF FONT',
    fontFamily: 'nunito',
    fontSize: 16,
    seed: 215,
  });

  // Excalifont
  elements.push({
    id: nextId(),
    type: 'text',
    x: tx + 150,
    y: ty + 90,
    width: 110,
    height: 45,
    angle: 0,
    strokeColor: '#ffffff',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 1,
    points: [],
    text: 'ANURAG SONI\nanurag soni',
    fontFamily: 'excalifont',
    fontSize: 22,
    seed: 216,
  });

  // comic shaans
  elements.push({
    id: nextId(),
    type: 'text',
    x: tx + 280,
    y: ty + 90,
    width: 110,
    height: 45,
    angle: 0,
    strokeColor: '#ffffff',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 1,
    points: [],
    text: 'ANURAG SONI\nanurag soni',
    fontFamily: 'comic-shanns',
    fontSize: 18,
    seed: 217,
  });

  // lillita one
  elements.push({
    id: nextId(),
    type: 'text',
    x: tx + 410,
    y: ty + 90,
    width: 110,
    height: 45,
    angle: 0,
    strokeColor: '#ffffff',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 1,
    points: [],
    text: 'ANURAG SONI\nanurag soni',
    fontFamily: 'lilita-one',
    fontSize: 19,
    seed: 218,
  });

  // nunito
  elements.push({
    id: nextId(),
    type: 'text',
    x: tx + 545,
    y: ty + 90,
    width: 110,
    height: 45,
    angle: 0,
    strokeColor: '#ffffff',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 1,
    points: [],
    text: 'ANURAG SONI\nanurag soni',
    fontFamily: 'nunito',
    fontSize: 18,
    seed: 219,
  });

  // Presentation Frame 1: Circuit Schematic & Derivation
  elements.push({
    id: 'frame_slide_1',
    type: 'frame',
    x: 110,
    y: 100,
    width: 710,
    height: 410,
    angle: 0,
    strokeColor: '#6965db',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'dashed',
    roughness: 0,
    opacity: 1,
    points: [],
    seed: 301,
    frameTitle: 'Slide 1: RLC Circuit Topology',
    frameIndex: 1,
  });

  // Presentation Frame 2: 4-Font Typography Comparison
  elements.push({
    id: 'frame_slide_2',
    type: 'frame',
    x: 110,
    y: 540,
    width: 710,
    height: 310,
    angle: 0,
    strokeColor: '#6965db',
    backgroundColor: 'transparent',
    fillStyle: 'transparent',
    strokeWidth: 2,
    strokeStyle: 'dashed',
    roughness: 0,
    opacity: 1,
    points: [],
    seed: 302,
    frameTitle: 'Slide 2: Typography & Lettering Showcase',
    frameIndex: 2,
  });

  return elements;
}

export const CIRCUIT_SCHEMATIC_PRESET = getInitialElements();

